version: '3.8'

services:
  yii2-app:
    image: voyzer10/yii2-app:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

